### ISSUE TITLE
CMD Problems 

### ISSUE THREAD

**Issue by S00154171** [kiswa/recipes#2]
Iv downloaded all the requirements and it still fails to launch it's giving me this error in the cmd when executing NPM install and gulp
![33234382-c57128e0-d21d-11e7-899d-20ec9b07a044](https://user-images.githubusercontent.com/14293256/33234405-29b86926-d21e-11e7-99d3-65851b732eed.png)

help would be greatly appreciated

**Comment by kiswa** [comment]
The error says you need to have PHP installed.

**Comment by S00154171** [comment]
I hate to be a burden but I'm new to this and would really enjoy getting the application working I have downloaded Apache and PHP and installed them properly now these are the errors I'm getting below
![image](https://user-images.githubusercontent.com/14293256/33277869-bd8c5008-d391-11e7-8c29-abad3a17dc92.png)

![image](https://user-images.githubusercontent.com/14293256/33277892-cbce472a-d391-11e7-87b3-75000d0e3ffe.png)

**Comment by kiswa** [comment]
The first one should be taken care of here: https://getcomposer.org/download/

The second one is a peer dependency that I should update the `package.json` to include. In the meantime, run `npm i -D node-normalize-scss` to install the missing dependency.

**Comment by S00154171** [comment]
okay so i did that now I'm just getting this
![image](https://user-images.githubusercontent.com/14293256/33284409-e9e3e980-d3a6-11e7-8756-6e961980e545.png)

**Comment by kiswa** [comment]
So... this project seems to be in need of some updating. Until I can get to that, try the following.

Open `gulpfile.js` and change lines 83-84 from this:

```javascript
                neat,
                scss_base
```

to this:

```javascript
                neat,
                'node_modules/node-normalize-scss/',
                scss_base
```

Hopefully that will get it working.

**Comment by S00154171** [comment]
did that work for you?
![image](https://user-images.githubusercontent.com/14293256/33290917-2262bf92-d3bc-11e7-813d-8fcd692ba596.png)
![image](https://user-images.githubusercontent.com/14293256/33290933-2e9f19cc-d3bc-11e7-88be-5cce55dbf657.png)

**Comment by kiswa** [comment]
Those warnings shouldn't prevent things from working.

**Comment by kiswa** [comment]
To verify, I made the changes listed above and it works (even with those warnings).

I'm about to make a check-in to take care of that, but this repo is seriously out-of-date and I should probably rework it to use non-deprecated dependencies.

**Comment by S00154171** [comment]
Hi, I'm sorry but how to I start the project now Ng serve doesn't work it
says I need to be inside the cli.

**Comment by kiswa** [comment]
It expects to be hosted by a webserver (*e.g.* Apache) with PHP for the backend.

**Comment by S00154171** [comment]
How do I do that?

**Comment by kiswa** [comment]
https://www.apachefriends.org/index.html
